pub struct MarketConfig {
    pub exchange_id: &'static str,
    pub index_symbol: &'static str,
    pub country_code: &'static str,
    pub base_market_cap: f64, // In USD
}

pub const MARKET_REGISTRY: &[MarketConfig] = &[
    MarketConfig { exchange_id: "NYSE", index_symbol: "^GSPC", country_code: "US", base_market_cap: 25.5e12 },
    MarketConfig { exchange_id: "NASDAQ", index_symbol: "^IXIC", country_code: "US", base_market_cap: 21.2e12 },
    MarketConfig { exchange_id: "KRX", index_symbol: "^KS11", country_code: "KR", base_market_cap: 1.8e12 },
    MarketConfig { exchange_id: "JPX", index_symbol: "^N225", country_code: "JP", base_market_cap: 6.2e12 },
    MarketConfig { exchange_id: "LSE", index_symbol: "^FTSE", country_code: "GB", base_market_cap: 3.2e12 },
    MarketConfig { exchange_id: "FWB", index_symbol: "^GDAXI", country_code: "DE", base_market_cap: 2.1e12 },
    MarketConfig { exchange_id: "HKEX", index_symbol: "^HSI", country_code: "HK", base_market_cap: 4.5e12 },
    MarketConfig { exchange_id: "SSE", index_symbol: "000001.SS", country_code: "CN", base_market_cap: 7.2e12 },
    MarketConfig { exchange_id: "TSX", index_symbol: "^GSPTSE", country_code: "CA", base_market_cap: 3.1e12 },
    MarketConfig { exchange_id: "ASX", index_symbol: "^AXJO", country_code: "AU", base_market_cap: 1.6e12 },
    MarketConfig { exchange_id: "EURONEXT", index_symbol: "^AEX", country_code: "NL", base_market_cap: 6.4e12 },
    MarketConfig { exchange_id: "SZSE", index_symbol: "399001.SZ", country_code: "CN", base_market_cap: 4.8e12 },
    MarketConfig { exchange_id: "BSE", index_symbol: "^BSESN", country_code: "IN", base_market_cap: 3.8e12 },
    MarketConfig { exchange_id: "NSE", index_symbol: "^NSEI", country_code: "IN", base_market_cap: 3.8e12 },
    MarketConfig { exchange_id: "TADAWUL", index_symbol: "^TASI.SR", country_code: "SA", base_market_cap: 2.7e12 },
    MarketConfig { exchange_id: "SIX", index_symbol: "^SSMI", country_code: "CH", base_market_cap: 1.9e12 },
    MarketConfig { exchange_id: "TWSE", index_symbol: "^TWII", country_code: "TW", base_market_cap: 1.8e12 },
    MarketConfig { exchange_id: "B3", index_symbol: "^BVSP", country_code: "BR", base_market_cap: 0.9e12 },
    MarketConfig { exchange_id: "JSE", index_symbol: "^J200.JO", country_code: "ZA", base_market_cap: 1.1e12 },
    MarketConfig { exchange_id: "BME", index_symbol: "^IBEX", country_code: "ES", base_market_cap: 0.8e12 },
    MarketConfig { exchange_id: "IDX", index_symbol: "^JKSE", country_code: "ID", base_market_cap: 0.6e12 },
    MarketConfig { exchange_id: "SGX", index_symbol: "^STI", country_code: "SG", base_market_cap: 0.6e12 },
    MarketConfig { exchange_id: "SET", index_symbol: "^SET.BK", country_code: "TH", base_market_cap: 0.5e12 },
    MarketConfig { exchange_id: "BIST", index_symbol: "XU100.IS", country_code: "TR", base_market_cap: 0.3e12 },
    MarketConfig { exchange_id: "MYX", index_symbol: "^KLSE", country_code: "MY", base_market_cap: 0.4e12 },
    MarketConfig { exchange_id: "BMV", index_symbol: "^MXX", country_code: "MX", base_market_cap: 0.5e12 },
    MarketConfig { exchange_id: "TASE", index_symbol: "^TA125.TA", country_code: "IL", base_market_cap: 0.2e12 },
    MarketConfig { exchange_id: "WSE", index_symbol: "^WIG20", country_code: "PL", base_market_cap: 0.2e12 },
    MarketConfig { exchange_id: "PSE", index_symbol: "^PSEI.PS", country_code: "PH", base_market_cap: 0.3e12 },
];
